hash-format = "sha256"

[[files]]
file = "mods/ae2.pw.toml"
hash = "74bbdad7434bc02ec767c15c0136269f885331601f73fa2365252c24e58c09bd"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "33fbfba45630792a9223d4e20c9300bc9fef142c68781fc648c32b62313f3e16"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/cloudsolutions.pw.toml"
hash = "be27a5254ee2b5cde48547e287cf10b31248ac37041bf6222ac21d586f5dd1c3"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "b6e7510c72ef37caaad62e2389a1959e40b71e47e1b2266a88174fa361895613"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1315cd56b0b4a5b3d53374cebf4f1f3cd0546b05058740847bd226c1d1ccab39"
metafile = true

[[files]]
file = "mods/digitalitems.pw.toml"
hash = "793fee9aa4767dfc06008a24338560559ff4051ecedc3c548e60c4a9094c4b2f"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "88f142bda6bfa6aff4f4d4e12b8ba7581aa40e3f163039a533f09dd6d634e093"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "5cc92eb0e58c2afbfd625d727d80da1d1c84500ec962bb22f5be28b864f18551"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "82ffc26ad624cdd846cbbeb99ed40ef44229ec7006a7ae7e8caa8df6409c20db"
metafile = true

[[files]]
file = "mods/modonomicon.pw.toml"
hash = "81da708e6a9add4237562e15bd2be857cfa3908c50951408ab2137ff1c68fbbd"
metafile = true

[[files]]
file = "mods/occultism.pw.toml"
hash = "9eec91e101a9fcf1edcafc6bbc4ead2ac1b11019593489dfc5f36ebe5996b4f1"
metafile = true

[[files]]
file = "mods/powah.pw.toml"
hash = "5f62a327932de16d603c5d922ff655069ac8fd8ccffb5f3f8b23f6cda4c04da0"
metafile = true

[[files]]
file = "mods/smartbrainlib.pw.toml"
hash = "8d3e9ef52ac3b65fb976629b55652ca30f9ad8b7ff37925c3111ae78386e1a97"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "131c818cca79586fdca0535062a63581e7c438efd108be4403ab8faea92e6368"
metafile = true

[[files]]
file = "mods/turtlematic.pw.toml"
hash = "eb08cadc1c87d76b108b01fd720217a43774fad2c0dbd7fe3535252aed16bad1"
metafile = true

[[files]]
file = "mods/unlimitedperipheralworks.pw.toml"
hash = "c75a580a65e0a9736026a3bb284d1746719695746aa020166c56eddc0f300b48"
metafile = true
