name = "Fabric Creative 1.20"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4128d962832cd1df4d0df4a316bba9a3e1ed04f7b6d3e0d8ffae490db324b73"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
